steps:
- name: node:16.19.1
  entrypoint: npm
  args: ["install"]
- name: node:16.19.1
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'DATABASE_URL=${_DATABASE_URL}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"